### ISSUE TITLE
 Please add Flowee's services

### ISSUE THREAD

**Issue by zander** [bchinfo/bch.info#125]
The page doesn't list most of https://flowee.org services:  https://bch.info/en/developers

* Data and utilities:
  * https://www.npmjs.com/package/floweejs
* Rest-APIS:
   * http://rest.flowee.org
   * http://api.flowee.org
 * Network:
   * https://flowee.org/docs/hub/api/

Thanks

**Comment by merc1er** [comment]
Closing as most of these links are now down.
