### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by melroy89** [bchinfo/bch.info#169]
Missing a simple FAQ page

**Comment by merc1er** [comment]
Agreed.  
Could you come up with content for that?

**Comment by imaginaryusername** [comment]
Yup, the hard part is coming up with questions. If you can get us some questions we can fill in the answers no problem.

**Comment by danger89** [comment]
Sure no problem.

**Comment by merc1er** [comment]
Closing this as inactive.
