### ISSUE TITLE
Need some help for wallet address convert.

### ISSUE THREAD

**Issue by zydjohnHotmail** [bchinfo/bch.info#177]
Hello:
I found one deposit address for Bitcon Cash Node, its address was: 16ZpRtEaXzVTaBTqYKkdUyU2mJqsTAvyyL

And I see there is a Bitcoin Cash explorer at: https://explorer.bitcoinverde.org/
So I input the address in the web link, so the link looks like this:
https://explorer.bitcoinverde.org/?search=16ZpRtEaXzVTaBTqYKkdUyU2mJqsTAvyyL
Then I got this new address returned on the web page:
bitcoincash:qq7smzqd92xcsufpt4ghpq30434ne5fkvqes7mssmk 

I want to know what this means, it seems the original address really is a Bitcoin Cash address, and it can be converted to the new address starting with bitcoincash:?
By the way, what is the difference between Bitcoin Cash and Bitcoin Cash Node?
Please advise,
Thanks,

**Comment by imaginaryusername** [comment]
This issues list is not a support helpdesk. Please keep the issues to website-related inquiries only.
