### ISSUE TITLE
Site doesn't appear to pickup user's preferred language.

### ISSUE THREAD

**Issue by 2qx** [bchinfo/bch.info#204]
![image](https://github.com/bchinfo/bch.info/assets/57997077/7eb4f1ed-0fe9-4679-80c1-af32a66b94cf)

If making a request with a language set in the browser, https://bch.info doesn't appear to pickup a user's preferred `accept language` setting and simply redirects (301) to https://bch.info/en/

**Comment by merc1er** [comment]
> I've attempted to fix this here, and although it "works on my machine", it doesn't appear to handle the redirect rules in the netlify preview.
> 
> #205

I just tested this and it worked on the Netlify preview for me. I've merged #205, you can confirm if it works for you on bch.info.
