### ISSUE TITLE
Add Bitcoin Cash Wallet from bitcoincashwallet.org to list of browser wallet links

### ISSUE THREAD

**Issue by cashaccount** [bchinfo/bch.info#212]
bitcoincashwallet.org hosts Bitcoin Cash Wallet which is a web wallet generated in the user's browser.

**Comment by merc1er** [comment]
I would be in favor of **NOT** adding it for the following reasons:
- no HTTPS
- looks unfinished (images don't load, outdated look...)
- redirects to external website for the "web wallet"
- not open source (at least no mention of a git repo anywhere)

![no](https://github.com/bchinfo/bch.info/assets/21960643/5f9f7ea8-c208-4aa2-a192-e14d2434ee73)

Closing this as there are too many red flags to even consider it, but maybe with enough additional links (e.g. to a GitHub repo) and trusted people in the community vouching for it, we could reopen and add.
