### ISSUE TITLE
New section for web wallets?

### ISSUE THREAD

**Issue by p0o** [bchinfo/bch.info#43]
I wanted to add mint.bitcoin.com and wallet.signup.cash wallet to the list but for that we need to create a new section for Web Wallets and add translation files for all the languages. 

So is it okay to do that?

**Comment by merc1er** [comment]
The translation files will automatically be added, you just need to add your content to the English file :)

Other than that, the new section works for me.

What do you think @imaginaryusername?

**Comment by imaginaryusername** [comment]
New section: Concept ack, we'll just need to evaluate the individual entries as we do entries in other wallet categories. Either someone from the team personally try, or have someone we know well try them.

**Comment by merc1er** [comment]
I am OK with mint.bitcoin.com and have used it successfully in the past.  
However wallet.signup.cash seems broken (see image below) and is not a popular option.

![Screenshot 2020-10-26 at 15 03 32](https://user-images.githubusercontent.com/21960643/97147759-978efe80-179c-11eb-9a3f-e0c667dde323.png)

**Comment by p0o** [comment]
@merc1er Oh, I can't replicate it on my side but I opened [an issue](https://github.com/signupcash/signup-core/issues/36) for it. Thanks for testing

>  is not a popular option.

It's pretty new, I can add a better reminder to users so they avoid putting large amounts of funds in it (if that helps?). The backup section also allow users to get a backup of it in Bitcoin.com wallet with a QR code. Also source code is [here](https://github.com/signupcash/signup-core/tree/master/packages/wallet)

**Comment by p0o** [comment]
Problem above is fixed, also added a disclaimer to the page that users top-up their wallet. Let me know if you guys are okay with adding it to the list or not.

![Screen Shot 2020-10-27 at 1 28 52 AM](https://user-images.githubusercontent.com/11336468/97206730-14999280-17f4-11eb-96ed-378e8fce45f3.png)

**Comment by imaginaryusername** [comment]
Thanks for the submission! I think mint.bitcoin.com had enough users for long enough it should be included no problem. Signup.cash, on the other end, is a _very_ new project - either a lot more user testimonies are needed, or more likely we should let it sit for a few weeks and make sure it's active and well-maintained before inclusion. Does that sound okay @p0o ?

**Comment by p0o** [comment]
@imaginaryusername Sure I'm fine with that, there are already a handful of users using it in China but yes it's pretty much new and under development.

**Comment by p0o** [comment]
@imaginaryusername May I know if you are still interested in adding Signup? 7 months later and lots of new commits and features added to signup:

https://github.com/signupcash/signup-core
https://docs.signup.cash/
https://signup.cash

We have an active support at hello@signup.cash with a respond rate of bellow 12 hours and estimated active uses of +200.

Feel free to try out the wallet, no registration required:
https://wallet.signup.cash

Thanks

**Comment by merc1er** [comment]
There is now a browser wallets section: https://bch.info/en/wallets.
