### ISSUE TITLE
Upgrade Statement Rewrite Proposal

### ISSUE THREAD

**Issue by p2pcashpig** [bchinfo/bch.info#46]
[Google](https://docs.google.com/document/d/15hLSvAOLG7deE9wAHrNtqj7pPScxaIm7NI2lSp5RxMA/edit#) (please refer to Google Docs)

Main Segment:

Urgent! Use the Correct Node Implementation to Keep Servicing The Bitcoin Cash Network

The Bitcoin Cash Network is undergoing a significant upgrade on the 15th of November.

Significantly, the Bitcoin ABC implementation intends to fork away with a 8% coinbase redirection to their own wallet.

This move has no consensus in the Bitcoin Cash Ecosystem.
 
On 15th November 2020, ABC intends to fork away with a coinbase reward that has no support from the current Bitcoin Cash ecosystem, ranked 5th on Coinmarketcap.

A majority of miners, businesses and critical lead developers of software with large Bitcoin Cash user bases have overwhelmingly signaled their support for using BCHN, or one of the other many compatible Bitcoin Cash Node Implementations.

Currently the BCH miner network is signaling overwhelmingly for BCHN.

To protect your users from experiencing an outage with the Bitcoin Cash network, it is best to switch to BCHN or any of the other Bitcoin Cash node.

Going ahead the Bitcoin Cash community will support bch.info to be the main portal for BCH related information, not bitcoincash.org

Developers who maintain SPV libraries will need to perform a minor upgrade to follow the new DAA specification. Some example implementations are available from the bitcoincashj maintainer (Java) and Electron Cash (Python).
 
Businesses that are Upgrading to BCHN:
 
(Logo Wall)
 
 
Links That Show The Bitcoin Cash Ecosystem Have Chosen BCHN:

Joint Statement from Miners

Signatures from Critical Bitcoin Cash Infrastructure Developers (CashFusion, Electron Cash, CashScript, and More) and More

Joint Statement from Simple Ledger Protocol (Primary BCH Token Solution with USDT Onboard)

Bitcoin.com Chooses BCHN Statement

Pools Signalling for BCHN

**Comment by merc1er** [comment]
@imaginaryusername what do you think?

**Comment by merc1er** [comment]
This would replace the content of the "upgrade" page, correct?

**Comment by imaginaryusername** [comment]
I don't think this should replace the upgrade statement - we can make this specifically address ABC concerns, while our previous upgrade announcement is more to the point on what people should actually be doing. Mixing the two may dilute the effects of each on the reader, I favor putting them side by side.

**Comment by merc1er** [comment]
I'll close this as no longer needed
