### ISSUE TITLE
List explorers

### ISSUE THREAD

**Issue by imaginaryusername** [bchinfo/bch.info#49]
Listing compatible explorers is likely a real need, let's list some (and tuck under "Individuals" in footer). 

Off the top of my head: 

https://explorer.bitcoin.com
https://www.blockchair.com/bitcoin-cash
https://bch.btc.com
https://explorer.viawallet.com/bch
https://www.blockchain.com/explorer?view=bch
https://explorer.bitcoinunlimited.info
https://www.bitcoinverde.org
https://explore.cash

**Comment by merc1er** [comment]
Let's link to https://explorer.bitcoinverde.org instead of BitcoinVerde.org?

**Comment by merc1er** [comment]
Done in #67
