### ISSUE TITLE
Add 1bit.group to exchanges

### ISSUE THREAD

**Issue by 1Bit-Group** [bchinfo/bch.info#95]
Hello
We are an automatic cryptocurrency exchange service, in our service users can exchange BitcoinCash BCH cryptocurrency for other cryptocurrencies without registration and AML / KYC, if possible, please add us to the section
exchanges
https://bch.info/en/exchanges

**Comment by merc1er** [comment]
Website defaults to Russian, is served over HTTP (http://1bit.group) and does not seem reputable.
